name: Test comosite actions
description: some desc

inputs:
  push-branches:
    description: some desc
    required: false
    default: "main,master"

outputs:
  push_branch_names:
    description: should output an array
    value: ${{ steps.op.push_branch_names }}


runs:
  using: composite
  steps:

    - name: op
      id: op
      shell: bash
      run: |
        push_branch_names=`echo \"${{ inputs.push-branches }}\" |sed 's/,/\", \"/g'`
        echo "push_branch_names='$push_branch_names'" >> $GITHUB_OUTPUT
      
    - name: print op
      shell: bash
      run: echo ${{ steps.op.outputs.push_branch_names }}

    - name: print inputs
      # if: github.event_name == 'push' && contains(fromJson('[${{ inputs.push-branches }}]'), 'main')
      if: contains(fromJson('[${{ steps.op.outputs.push_branch_names }}]'), 'main')
      shell: bash
      run: echo "yes"
