name: Test comosite actions
description: some desc

inputs:
  push-branches:
    description: some desc
    required: false
    default: "main,master"

runs:
  using: composite
  steps:
    - name: print inputs
      shell: bash
      run: echo fromJson('[${{ inputs.push-branches }}]')
