name: Test comosite actions
description: some desc

inputs:
  push-branches:
    description: some desc
    required: false
    default: "main,master"

runs:
  using: composite
  steps:
    - name: print inputs
      if: contains(fromJson('[${{ inputs.push-branches }}]'), "main")
      shell: bash
      run: echo "yes"
