name: Cloud-actions-push-to-s3-test
on:
  pull_request:
    paths:
      - somefile.txt
    types:
      - opened
      - edited
      - synchronize
      - closed

jobs:
  test-job:
    runs-on: ubuntu-20.04

    steps:
    - name: Run composite action
      uses: XanaduAI/cloud-actions/push-to-s3-and-invalidate-cloudfront@sc-28936-create-a-generic-github-action-to-push-frontend
      with:
        s3-bucket: "blah"
