name: Check if merging to main or staging only happens from staging or develop respectively
on:
  pull_request:
    branches:
      - main
      - staging
    types:
      - opened
      - edited
      - synchronize

jobs:
  merge_checks_staging:
    if: github.base.ref == "staging"
    runs-on: ubuntu-latest
    name: Check if the PR to staging is from the develop branch
    steps:
      - uses: XanaduAI/cloud-actions/restrict-merge-to-destination-branch@v1.1
        with:
          source-branch: develop
          destination-branch: staging

  merge_checks_prod:
    if: github.base.ref == "main"
    runs-on: ubuntu-latest
    name: Check if the PR to main is from the staging branch
    steps:
      - uses: XanaduAI/cloud-actions/restrict-merge-to-destination-branch@v1.1
        with:
          source-branch: staging
          destination-branch: main

