on:
  pull_request:
    branches:
      - main
jobs:
  merge_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the pull request is mergeable to master
        run: |
          if [[ "$GITHUB_HEAD_REF" == 'develop' ]]
          then
            exit 0
          else
            echo "PR to main should orignate from develop and not $BLAH"
            exit 1
          fi
